name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: ci pipeline
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: build
        run: go build ./...

      - name: unit test
        run: go test -race -gcflags=all=-l -coverprofile=coverage.out ./...

      - name: install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: update coverage on coveralls.io
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=coverage.out -service=github

  job2:
    name: security
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run gosec security scanner
        uses: securego/gosec@master
        with:
          args: ./...

