name: Go

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: ci pipeline
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: build
      run: go build ./...

    - name: unit test
      run: go test -race -gcflags=all=-l -covermode atomic -cover -coverprofile=coverage.out ./...

    - name: convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1

    - name: install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=github

